import { describe, it, expect } from 'vitest';
import { generatePolling } from '../../src/generator/polling.js';
import { generate } from '../../src/generator/index.js';

const sample = {
  token: 'tok123',
  messages: { m1: { text: 'hi', buttons: [{ text: 'Y', payload: 'btn_0' }] } },
  authPrompts: {},
  transitions: { m1: { btn_0: null } },
  initialNext: 'm1',
};

describe('generatePolling — Python/PTB output', () => {
  it('emits a PTB long-polling bot', () => {
    const code = generatePolling(sample);
    expect(code).toContain('# Generated by Bot Constructor for Telegram');
    expect(code).toContain('# pip install python-telegram-bot');
    expect(code).toContain('from telegram.ext import');
    expect(code).toContain('def build_app():');
    expect(code).toContain('app.run_polling()');
    expect(code).toContain('if __name__ == "__main__":');
    expect(code).toContain('os.environ.get("BOT_TOKEN")');
    expect(code).toContain('"tok123"');
  });

  it('embeds tables via json.loads including node ids and payloads', () => {
    const code = generatePolling(sample);
    expect(code).toContain('_TABLES = json.loads(');
    expect(code).toContain('m1');
    expect(code).toContain('btn_0');
  });
});

describe('generate(project)', () => {
  const project = (mode) => ({
    token: 'T', mode,
    nodes: [
      { id: 'start', type: 'start', data: {} },
      { id: 'm1', type: 'message', data: { text: 'hi', buttonsEnabled: false } },
    ],
    edges: [{ id: 'e0', source: 'start', target: 'm1' }],
  });
  it('dispatches to polling template for mode: "polling"', () => {
    expect(generate(project('polling'))).toContain('run_polling');
  });
  it('dispatches to webhook template for mode: "webhook"', () => {
    expect(generate(project('webhook'))).toContain('run_webhook');
  });

  it('generates SETTERS/CONDITIONS/INPUTS tables and advance()', () => {
    const project = {
      token: 'T', mode: 'polling',
      nodes: [
        { id: 'start', type: 'start', data: {} },
        { id: 's1', type: 'setvar', data: { variable: 'x', value: 'hi' } },
        { id: 'm1', type: 'message', data: { text: '{{x}}', buttonsEnabled: false } },
      ],
      edges: [
        { id: 'e0', source: 'start', target: 's1' },
        { id: 'e1', source: 's1', target: 'm1' },
      ],
    };
    const code = generate(project);
    expect(code).toContain('SETTERS = _TABLES["SETTERS"]');
    expect(code).toContain('CONDITIONS = _TABLES["CONDITIONS"]');
    expect(code).toContain('INPUTS = _TABLES["INPUTS"]');
    expect(code).toContain('async def advance(');
  });
});
