import { describe, it, expect } from 'vitest';
import { generateWebhook } from '../../src/generator/webhook.js';

const sample = {
  token: 'T',
  messages: {},
  authPrompts: { a1: { promptText: 'p', contactButton: { text: 'c' }, refusalButton: null } },
  transitions: { a1: { contact: null } },
  initialNext: 'a1',
};

describe('generateWebhook — Python/PTB output', () => {
  it('emits a PTB webhook bot on port 3000', () => {
    const code = generateWebhook(sample);
    expect(code).toContain('# Generated by Bot Constructor for Telegram');
    expect(code).toContain('def build_app():');
    expect(code).toContain('app.run_webhook(');
    expect(code).toContain('port=3000');
    expect(code).toContain('if __name__ == "__main__":');
  });

  it('carries the shared runtime (tables, auth, request_contact)', () => {
    const code = generateWebhook(sample);
    expect(code).toContain('_TABLES = json.loads(');
    expect(code).toContain('AUTH_PROMPTS');
    expect(code).toContain('request_contact=True');
    expect(code).toContain('def render(');
  });
});
