export function generatePolling({ token, messages, transitions, initialNext }) {
  const tables = `
const MESSAGES = ${JSON.stringify(messages, null, 2)};
const TRANSITIONS = ${JSON.stringify(transitions, null, 2)};
const INITIAL_NEXT = ${JSON.stringify(initialNext)};
`.trim();

  return `// Generated by Bot Constructor for Max
const TOKEN = ${JSON.stringify(token)};
const API = 'https://botapi.max.ru';
const userState = new Map();

${tables}

async function send(chatId, text, buttons) {
  const body = { recipient: { chatId }, text };
  if (buttons && buttons.length > 0) {
    body.attachments = [{
      type: 'inline_keyboard',
      payload: {
        buttons: [buttons.map(b => ({ text: b.text, payload: b.payload, type: 'callback' }))],
      },
    }];
  }
  await fetch(\`\${API}/messages?token=\${TOKEN}\`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
}

async function handle(chatId, payload) {
  const state = userState.get(chatId) ?? 'start';
  let next;
  if (state === 'start') {
    next = INITIAL_NEXT;
  } else {
    const trans = TRANSITIONS[state];
    if (!trans) return;
    next = trans[payload] ?? trans.default ?? null;
  }
  if (!next) {
    userState.set(chatId, 'start');
    return;
  }
  const m = MESSAGES[next];
  if (!m) return;
  await send(chatId, m.text, m.buttons);
  const nextTrans = TRANSITIONS[next];
  const hasAnyTarget = nextTrans && Object.values(nextTrans).some(v => v);
  userState.set(chatId, hasAnyTarget ? next : 'start');
}

let marker = 0;
if (!globalThis.__SKIP_POLL__) {
  (async () => {
    while (true) {
      try {
        const r = await fetch(\`\${API}/updates?token=\${TOKEN}&timeout=30&marker=\${marker}\`);
        const json = await r.json();
        if (json.marker) marker = json.marker;
        for (const u of json.updates ?? []) {
          const chatId = u.message?.recipient?.chat_id
            ?? u.message?.recipient?.chatId
            ?? u.callback?.message?.recipient?.chat_id
            ?? u.callback?.message?.recipient?.chatId;
          const payload = u.callback?.payload;
          if (chatId) await handle(chatId, payload);
        }
      } catch (e) {
        console.error('polling error:', e);
        await new Promise(res => setTimeout(res, 2000));
      }
    }
  })().catch((e) => { console.error('fatal:', e); process.exit(1); });
}
`;
}
