export function generatePolling({ token, messages, transitions, initialNext }) {
  const tables = `
const MESSAGES = ${JSON.stringify(messages, null, 2)};
const TRANSITIONS = ${JSON.stringify(transitions, null, 2)};
const INITIAL_NEXT = ${JSON.stringify(initialNext)};
`.trim();

  return `// Generated by Bot Constructor for Max
const TOKEN = ${JSON.stringify(token)};
const API = 'https://platform-api.max.ru';
const userState = new Map();

${tables}

async function send(chatId, text, buttons) {
  const body = { text };
  if (buttons && buttons.length > 0) {
    body.attachments = [{
      type: 'inline_keyboard',
      payload: {
        buttons: [buttons.map(b => ({ text: b.text, payload: b.payload, type: 'callback' }))],
      },
    }];
  }
  const r = await fetch(\`\${API}/messages?chat_id=\${chatId}\`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': TOKEN,
    },
    body: JSON.stringify(body),
  });
  if (!r.ok) console.error('send failed:', r.status, await r.text());
}

async function handle(chatId, payload) {
  const state = userState.get(chatId) ?? 'start';
  let next;
  if (state === 'start') {
    next = INITIAL_NEXT;
  } else {
    const trans = TRANSITIONS[state];
    if (!trans) return;
    next = trans[payload] ?? trans.default ?? null;
  }
  if (!next) {
    userState.set(chatId, 'start');
    return;
  }
  const m = MESSAGES[next];
  if (!m) return;
  await send(chatId, m.text, m.buttons);
  const nextTrans = TRANSITIONS[next];
  const hasAnyTarget = nextTrans && Object.values(nextTrans).some(v => v);
  userState.set(chatId, hasAnyTarget ? next : 'start');
}

let marker = 0;
if (!globalThis.__SKIP_POLL__) {
  (async () => {
    console.log(\`Бот запущен в режиме Long Polling. API: \${API}. Ожидание сообщений...\`);
    while (true) {
      try {
        const r = await fetch(\`\${API}/updates?timeout=30&marker=\${marker}\`, {
          headers: { 'Authorization': TOKEN },
        });
        if (!r.ok) {
          console.error('updates failed:', r.status, await r.text());
          await new Promise(res => setTimeout(res, 2000));
          continue;
        }
        const json = await r.json();
        if (json.marker) marker = json.marker;
        for (const u of json.updates ?? []) {
          if (u.update_type !== 'message_created' && u.update_type !== 'message_callback') continue;
          const chatId = u.chat_id
            ?? u.message?.recipient?.chat_id
            ?? u.message?.recipient?.chatId;
          const payload = u.callback?.payload ?? u.message_callback?.payload;
          if (!chatId) {
            console.error('no chat_id in update:', JSON.stringify(u));
            continue;
          }
          await handle(chatId, payload);
        }
      } catch (e) {
        console.error('polling error:', e);
        await new Promise(res => setTimeout(res, 2000));
      }
    }
  })().catch((e) => { console.error('fatal:', e); process.exit(1); });
}
`;
}
