export function botRuntime({ token, messages, authPrompts = {}, transitions, initialNext }) {
  const tables = {
    MESSAGES: messages,
    AUTH_PROMPTS: authPrompts,
    TRANSITIONS: transitions,
    INITIAL_NEXT: initialNext,
  };
  const tablesLiteral = JSON.stringify(JSON.stringify(tables));

  return `# Generated by Bot Constructor for Telegram
# pip install python-telegram-bot
# Состояние (user_state) и переменные (user_vars) хранятся в памяти процесса и теряются при перезапуске.
import os
import re
import json

from telegram import (
    InlineKeyboardButton,
    InlineKeyboardMarkup,
    KeyboardButton,
    ReplyKeyboardMarkup,
    ReplyKeyboardRemove,
)
from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    CallbackQueryHandler,
    filters,
)

TOKEN = os.environ.get("BOT_TOKEN") or ${JSON.stringify(token)}

_TABLES = json.loads(${tablesLiteral})
MESSAGES = _TABLES["MESSAGES"]
AUTH_PROMPTS = _TABLES["AUTH_PROMPTS"]
TRANSITIONS = _TABLES["TRANSITIONS"]
INITIAL_NEXT = _TABLES["INITIAL_NEXT"]

user_state = {}
user_vars = {}


def render(text, chat_id):
    vars_ = user_vars.get(chat_id, {})
    return re.sub(r"\\{\\{(\\w+)\\}\\}", lambda m: str(vars_.get(m.group(1), "")), str(text))


def message_markup(msg):
    buttons = msg.get("buttons")
    if not buttons:
        return ReplyKeyboardRemove()
    rows = [[InlineKeyboardButton(b["text"], callback_data=b["payload"])] for b in buttons]
    return InlineKeyboardMarkup(rows)


def auth_markup(prompt):
    rows = [[KeyboardButton(prompt["contactButton"]["text"], request_contact=True)]]
    if prompt.get("refusalButton"):
        rows.append([KeyboardButton(prompt["refusalButton"]["text"])])
    return ReplyKeyboardMarkup(rows, resize_keyboard=True, one_time_keyboard=True)


async def send(context, chat_id, text, reply_markup):
    await context.bot.send_message(chat_id=chat_id, text=text, reply_markup=reply_markup)


async def handle(update, context):
    if update.callback_query:
        await update.callback_query.answer()
    chat_id = update.effective_chat.id
    message = update.message
    text = message.text if message else None
    contact = message.contact if message else None
    data = update.callback_query.data if update.callback_query else None

    if text == "/start":
        user_state[chat_id] = "start"
    state = user_state.get(chat_id, "start")
    nxt = None

    if state == "start":
        nxt = INITIAL_NEXT
    elif state in AUTH_PROMPTS:
        prompt = AUTH_PROMPTS[state]
        if contact:
            prev = user_vars.get(chat_id, {})
            user_vars[chat_id] = {
                **prev,
                "first_name": contact.first_name or "",
                "last_name": contact.last_name or "",
                "phone": str(contact.phone_number or ""),
            }
            nxt = TRANSITIONS.get(state, {}).get("contact")
        elif prompt.get("refusalButton") and text == prompt["refusalButton"]["text"]:
            nxt = TRANSITIONS.get(state, {}).get("refused")
        else:
            return
    elif state in MESSAGES:
        if contact:
            return
        trans = TRANSITIONS.get(state)
        if not trans:
            return
        nxt = trans.get(data)
        if nxt is None:
            nxt = trans.get("default")
    else:
        return

    if not nxt:
        user_state[chat_id] = "start"
        return

    if nxt in AUTH_PROMPTS:
        prompt = AUTH_PROMPTS[nxt]
        await send(context, chat_id, render(prompt["promptText"], chat_id), auth_markup(prompt))
    elif nxt in MESSAGES:
        m = MESSAGES[nxt]
        await send(context, chat_id, render(m["text"], chat_id), message_markup(m))
    else:
        user_state[chat_id] = "start"
        return

    next_trans = TRANSITIONS.get(nxt)
    has_any = bool(next_trans) and any(next_trans.values())
    user_state[chat_id] = nxt if has_any else "start"


def build_app():
    app = Application.builder().token(TOKEN).build()
    app.add_handler(CommandHandler("start", handle))
    app.add_handler(MessageHandler(filters.CONTACT, handle))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle))
    app.add_handler(CallbackQueryHandler(handle))
    return app
`;
}
