export function botRuntime({
  token,
  messages,
  authPrompts = {},
  setters = {},
  inputs = {},
  conditions = {},
  transitions,
  initialNext,
}) {
  const tables = {
    MESSAGES: messages,
    AUTH_PROMPTS: authPrompts,
    SETTERS: setters,
    INPUTS: inputs,
    CONDITIONS: conditions,
    TRANSITIONS: transitions,
    INITIAL_NEXT: initialNext,
  };
  const tablesLiteral = JSON.stringify(JSON.stringify(tables));

  return `# Generated by Bot Constructor for Telegram
# pip install python-telegram-bot
# Состояние (user_state) и переменные (user_vars) хранятся в памяти процесса и теряются при перезапуске.
import os
import re
import json

from telegram import (
    InlineKeyboardButton,
    InlineKeyboardMarkup,
    KeyboardButton,
    ReplyKeyboardMarkup,
    ReplyKeyboardRemove,
)
from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    CallbackQueryHandler,
    filters,
)

TOKEN = os.environ.get("BOT_TOKEN") or ${JSON.stringify(token)}

_TABLES = json.loads(${tablesLiteral})
MESSAGES = _TABLES["MESSAGES"]
AUTH_PROMPTS = _TABLES["AUTH_PROMPTS"]
SETTERS = _TABLES["SETTERS"]
INPUTS = _TABLES["INPUTS"]
CONDITIONS = _TABLES["CONDITIONS"]
TRANSITIONS = _TABLES["TRANSITIONS"]
INITIAL_NEXT = _TABLES["INITIAL_NEXT"]

user_state = {}
user_vars = {}


def render(text, chat_id):
    vars_ = user_vars.get(chat_id, {})
    return re.sub(r"\\{\\{(\\w+)\\}\\}", lambda m: str(vars_.get(m.group(1), "")), str(text))


def set_var(chat_id, name, value):
    prev = user_vars.get(chat_id, {})
    user_vars[chat_id] = {**prev, name: value}


def check_rule(chat_id, rule):
    left = str(user_vars.get(chat_id, {}).get(rule["variable"], ""))
    op = rule["op"]
    if op == "empty":
        return left.strip() == ""
    if op == "not_empty":
        return left.strip() != ""
    right = render(rule["value"], chat_id)
    if op in ("gt", "lt", "gte", "lte"):
        try:
            lf, rf = float(left), float(right)
        except ValueError:
            return False
        return {"gt": lf > rf, "lt": lf < rf, "gte": lf >= rf, "lte": lf <= rf}[op]
    a, b = left.strip().lower(), right.strip().lower()
    if op == "equals":
        return a == b
    if op == "not_equals":
        return a != b
    if op == "contains":
        return b in a
    if op == "not_contains":
        return b not in a
    return False


def eval_condition(chat_id, node):
    trans = TRANSITIONS.get(node, {})
    for i, rule in enumerate(CONDITIONS[node]["rules"]):
        if check_rule(chat_id, rule):
            return trans.get(f"rule_{i}")
    return trans.get("else")


def message_markup(msg):
    buttons = msg.get("buttons")
    if not buttons:
        return ReplyKeyboardRemove()
    rows = [[InlineKeyboardButton(b["text"], callback_data=b["payload"])] for b in buttons]
    return InlineKeyboardMarkup(rows)


def auth_markup(prompt):
    rows = [[KeyboardButton(prompt["contactButton"]["text"], request_contact=True)]]
    if prompt.get("refusalButton"):
        rows.append([KeyboardButton(prompt["refusalButton"]["text"])])
    return ReplyKeyboardMarkup(rows, resize_keyboard=True, one_time_keyboard=True)


async def send(context, chat_id, text, reply_markup):
    await context.bot.send_message(chat_id=chat_id, text=text, reply_markup=reply_markup)


async def advance(context, chat_id, node):
    for _ in range(1000):
        if not node:
            break
        if node in SETTERS:
            s = SETTERS[node]
            set_var(chat_id, s["variable"], render(s["value"], chat_id))
            node = TRANSITIONS.get(node, {}).get("default")
            continue
        if node in CONDITIONS:
            node = eval_condition(chat_id, node)
            continue
        if node in AUTH_PROMPTS:
            prompt = AUTH_PROMPTS[node]
            await send(context, chat_id, render(prompt["promptText"], chat_id), auth_markup(prompt))
        elif node in INPUTS:
            await send(context, chat_id, render(INPUTS[node]["promptText"], chat_id), ReplyKeyboardRemove())
        elif node in MESSAGES:
            m = MESSAGES[node]
            await send(context, chat_id, render(m["text"], chat_id), message_markup(m))
        else:
            break
        next_trans = TRANSITIONS.get(node)
        has_any = bool(next_trans) and any(next_trans.values())
        user_state[chat_id] = node if has_any else "start"
        return
    user_state[chat_id] = "start"


async def handle(update, context):
    if update.callback_query:
        await update.callback_query.answer()
    chat_id = update.effective_chat.id
    message = update.message
    text = message.text if message else None
    contact = message.contact if message else None
    data = update.callback_query.data if update.callback_query else None

    if text == "/start":
        user_state[chat_id] = "start"
    state = user_state.get(chat_id, "start")
    nxt = None

    if state == "start":
        nxt = INITIAL_NEXT
    elif state in AUTH_PROMPTS:
        prompt = AUTH_PROMPTS[state]
        if contact:
            prev = user_vars.get(chat_id, {})
            user_vars[chat_id] = {
                **prev,
                "first_name": contact.first_name or "",
                "last_name": contact.last_name or "",
                "phone": str(contact.phone_number or ""),
            }
            nxt = TRANSITIONS.get(state, {}).get("contact")
        elif prompt.get("refusalButton") and text == prompt["refusalButton"]["text"]:
            nxt = TRANSITIONS.get(state, {}).get("refused")
        else:
            return
    elif state in INPUTS:
        if text is None:
            return
        set_var(chat_id, INPUTS[state]["variable"], text)
        nxt = TRANSITIONS.get(state, {}).get("default")
    elif state in MESSAGES:
        if contact:
            return
        trans = TRANSITIONS.get(state)
        if not trans:
            return
        nxt = trans.get(data)
        if nxt is None:
            nxt = trans.get("default")
    else:
        return

    await advance(context, chat_id, nxt)


def build_app():
    app = Application.builder().token(TOKEN).build()
    app.add_handler(CommandHandler("start", handle))
    app.add_handler(MessageHandler(filters.CONTACT, handle))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle))
    app.add_handler(CallbackQueryHandler(handle))
    return app
`;
}
