export function generateWebhook({ token, messages, transitions, initialNext }) {
  const tables = `
const MESSAGES = ${JSON.stringify(messages, null, 2)};
const TRANSITIONS = ${JSON.stringify(transitions, null, 2)};
const INITIAL_NEXT = ${JSON.stringify(initialNext)};
`.trim();

  return `// Generated by Bot Constructor for Max
const http = require('http');
const TOKEN = ${JSON.stringify(token)};
const API = 'https://botapi.max.ru';
const userState = new Map();

${tables}

async function send(chatId, text, buttons) {
  const body = { recipient: { chatId }, text };
  if (buttons && buttons.length > 0) {
    body.attachments = [{
      type: 'inline_keyboard',
      payload: {
        buttons: [buttons.map(b => ({ text: b.text, payload: b.payload, type: 'callback' }))],
      },
    }];
  }
  await fetch(\`\${API}/messages?token=\${TOKEN}\`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
}

async function handle(chatId, payload) {
  const state = userState.get(chatId) ?? 'start';
  let next;
  if (state === 'start') {
    next = INITIAL_NEXT;
  } else {
    const trans = TRANSITIONS[state];
    if (!trans) return;
    next = trans[payload] ?? trans.default ?? null;
  }
  if (!next) { userState.set(chatId, 'start'); return; }
  const m = MESSAGES[next];
  if (!m) return;
  await send(chatId, m.text, m.buttons);
  const nextTrans = TRANSITIONS[next];
  const hasAnyTarget = nextTrans && Object.values(nextTrans).some(v => v);
  userState.set(chatId, hasAnyTarget ? next : 'start');
}

const server = http.createServer((req, res) => {
  if (req.method !== 'POST') { res.writeHead(405); res.end(); return; }
  let body = '';
  req.on('data', c => body += c);
  req.on('end', async () => {
    try {
      const u = JSON.parse(body);
      const chatId = u.message?.recipient?.chat_id
        ?? u.message?.recipient?.chatId
        ?? u.callback?.message?.recipient?.chat_id
        ?? u.callback?.message?.recipient?.chatId;
      const payload = u.callback?.payload;
      if (chatId) await handle(chatId, payload);
      res.writeHead(200); res.end('ok');
    } catch (e) {
      console.error('webhook error:', e);
      res.writeHead(500); res.end();
    }
  });
});

server.listen(3000, () => console.log('Webhook server on :3000'));
`;
}
