export function generateWebhook({ token, messages, transitions, initialNext }) {
  const tables = `
const MESSAGES = ${JSON.stringify(messages, null, 2)};
const TRANSITIONS = ${JSON.stringify(transitions, null, 2)};
const INITIAL_NEXT = ${JSON.stringify(initialNext)};
`.trim();

  return `// Generated by Bot Constructor for Max
const http = require('http');
const TOKEN = ${JSON.stringify(token)};
const API = 'https://platform-api.max.ru';
const userState = new Map();

${tables}

async function send(chatId, text, buttons) {
  const body = { text };
  if (buttons && buttons.length > 0) {
    body.attachments = [{
      type: 'inline_keyboard',
      payload: {
        buttons: [buttons.map(b => ({ text: b.text, payload: b.payload, type: 'callback' }))],
      },
    }];
  }
  const r = await fetch(\`\${API}/messages?chat_id=\${chatId}\`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': TOKEN,
    },
    body: JSON.stringify(body),
  });
  if (!r.ok) console.error('send failed:', r.status, await r.text());
}

async function handle(chatId, payload) {
  const state = userState.get(chatId) ?? 'start';
  let next;
  if (state === 'start') {
    next = INITIAL_NEXT;
  } else {
    const trans = TRANSITIONS[state];
    if (!trans) return;
    next = trans[payload] ?? trans.default ?? null;
  }
  if (!next) { userState.set(chatId, 'start'); return; }
  const m = MESSAGES[next];
  if (!m) return;
  await send(chatId, m.text, m.buttons);
  const nextTrans = TRANSITIONS[next];
  const hasAnyTarget = nextTrans && Object.values(nextTrans).some(v => v);
  userState.set(chatId, hasAnyTarget ? next : 'start');
}

const server = http.createServer((req, res) => {
  if (req.method !== 'POST') { res.writeHead(405); res.end(); return; }
  let body = '';
  req.on('data', c => body += c);
  req.on('end', async () => {
    try {
      const u = JSON.parse(body);
      if (u.update_type !== 'message_created' && u.update_type !== 'message_callback') {
        res.writeHead(200); res.end('ignored');
        return;
      }
      const chatId = u.chat_id
        ?? u.message?.recipient?.chat_id
        ?? u.message?.recipient?.chatId;
      const payload = u.callback?.payload ?? u.message_callback?.payload;
      if (!chatId) {
        console.error('no chat_id in update:', JSON.stringify(u));
        res.writeHead(200); res.end('ignored');
        return;
      }
      await handle(chatId, payload);
      res.writeHead(200); res.end('ok');
    } catch (e) {
      console.error('webhook error:', e);
      res.writeHead(500); res.end();
    }
  });
});

server.listen(3000, () => console.log('Webhook server on :3000'));
`;
}
